### ISSUE TITLE
Is this repo needed?

### ISSUE THREAD

**Issue by ravi-prakash-v** [dhp-project/DHP-Gateway#2]
Hi @pramodkvarma is this repo needed? Since the gateway is sector-agnostic, can't DHP implementors simply fork from the reference BG present in the beckn account?

**Comment by pramodkvarma** [comment]
Yes of course. No need to maintain a fork/copy. Just point the community to reference Gateway repo. You can delete the repo.

**Comment by ravi-prakash-v** [comment]
Deleting this repo.
